### PR TITLE
Update vw_spectra.py

### PR DESCRIPTION
**Pull request by qezlou**
Do we need this modification ? When I was running this code, I got the error :
```
TypeError: __init__() missing 2 required positional arguments: 'cofm' and 'axis'

```
So, we need to pass the arguments of Spectra to it. Am I right ?

I just copied these two lines form fake_spectra.plot_spectra

### CODE REVIEW

**Comment by sbird** [comment]
A very good idea! I will merge it, thanks!

**Comment by qezlou** [comment]
You're welcome!
There is something else I have been struggling with over the weekend.

After the modification above, I can successfully make an instant of this class as:

```
 vv = vw_spectra.VWSpectra(num = snaps[i], base="./output/",savedir="./postprocessing/randspectra/Snap_018/ratenetworkspectra/",savefile="spectra_"+str(snaps[i])+"_all.hdf5", kernel='tophat')

```
the outcome shows the spectra has been loaded successfully:
```
2000  sightlines. resolution:  1.0000788653364747  z= 4.664517702470927
```
But, when I call:

```
vv.vel_width_hist(elem='H', ion=1) 
```
Which I expect to load from spectra since we already have HII printed there.

I get errors:
```
~/.local/lib/python3.6/site-packages/fake_spectra/spectra.py in _really_load_array(self, key, array, array_name)
    315         #First check it was not already loaded
--> 316         if np.size(array[key]) > 1:
    317             return

KeyError: ('H', 1)

```
and:

```
~/.local/lib/python3.6/site-packages/fake_spectra/spectra.py in particles_near_lines(self, pos, hh, axis, cofm)
    588         assert np.min(axis) > 0
    589         assert np.max(axis) <4
--> 590         ind = _near_lines(self.box, pos, hh, axis, cofm)
    591         return ind
    592 

ValueError: cofm must have 64-bit float type and axis must be a 32-bit integer

```
The errors are the same when I call for the Si II. 
I have checked on the last error and found even when I am calling any methods from ```fake_spectra.plot_spectra``` the cofm and axis loaded are float 32, but I do not get any errors there.

**Comment by sbird** [comment]
Why don't you do a %debug and look at which array it is that is not loaded?

**Comment by qezlou** [comment]
Sorry, do you mean the cofm and axis arrays ?

Respectively, they are:

```
array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       ...,
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]], dtype=float32)
       
       
       array([1., 1., 1., ..., 1., 1., 1.], dtype=float32
       
```
In both vw_spectra and plot_spectra calls.

**Comment by sbird** [comment]
No, I mean here:
  315         #First check it was not already loaded
--> 316         if np.size(array[key]) > 1:
    317             return
what is array[key]?

**Comment by sbird** [comment]
You expected that really_load_array will not need to load anything from disc, but why did you expect this? What is the array that it is trying to load from disc and why does it need to load it from disc?

**Comment by qezlou** [comment]
Oh, yes. That array is tau_obs which is an empty array in the saved spectra. So, I assume I need to regenerate the spectra and print the tau_obs on them. But, I could not find any method like Spectra.get_tau() to calculate it. Actually, I am not sure what quantity is that.

**Comment by qezlou** [comment]
> Oh, yes. That array is tau_obs which is an empty array in the saved spectra. So, I assume I need to regenerate the spectra and print the tau_obs on them. But, I could not find any method like Spectra.get_tau() to calculate it. Actually, I am not sure what quantity is that.

Oh, I guess I should just make sure the ```force_compute``` is ```True```, then the ```vw_spectra.get_observer_tau()``` should calculate it

**Comment by qezlou** [comment]
> > Oh, yes. That array is tau_obs which is an empty array in the saved spectra. So, I assume I need to regenerate the spectra and print the tau_obs on them. But, I could not find any method like Spectra.get_tau() to calculate it. Actually, I am not sure what quantity is that.
> 
> Oh, I guess I should just make sure the `force_compute` is `True`, then the `vw_spectra.get_observer_tau()` should calculate it

I tried it. Actually, it does not make any difference. Because if it does not already exist, however, a ```key Error``` will be raised and therefore it recomputes the tau_obs.  

So, I think the first ```Key Error``` makes sense and we should not be worried about it. But, I do not know the source of the second error regarding the type of cofm and axis

**Comment by sbird** [comment]
Looks like cofm is float32 instead of float64. But it looks weird in other ways too - why is cofm all zeros?

**Comment by qezlou** [comment]
Yes. I agree it should have loaded cofm. But, even in the case of calling PlottingSpectra, these values were the same, but I never got errors there, and plots were done properly.

```
ipdb> tt =  PlottingSpectra(snaps[i], base="/rhome/mqezl001/bigdata/TNG/TNG100-1/output", savedir="../TNG/", savefile="spectra_"+str(snaps[i])+"_all_new_thresh_2000.hdf5", kernel = 'tophat')

ipdb> tt.cofm
array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       ...,
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]], dtype=float32)
ipdb> tt.axis
array([1., 1., 1., ..., 1., 1., 1.], dtype=float32)

```

**Comment by qezlou** [comment]
> Yes. I agree it should have loaded cofm. But, even in the case of calling PlottingSpectra, these values were the same, but I never got errors there, and plots were done properly.
> 
> ```
> ipdb> tt =  PlottingSpectra(snaps[i], base="/rhome/mqezl001/bigdata/TNG/TNG100-1/output", savedir="../TNG/", savefile="spectra_"+str(snaps[i])+"_all_new_thresh_2000.hdf5", kernel = 'tophat')
> 
> ipdb> tt.cofm
> array([[0., 0., 0.],
>        [0., 0., 0.],
>        [0., 0., 0.],
>        ...,
>        [0., 0., 0.],
>        [0., 0., 0.],
>        [0., 0., 0.]], dtype=float32)
> ipdb> tt.axis
> array([1., 1., 1., ..., 1., 1., 1.], dtype=float32)
> ```

I checked the ```['spectra']['cofm']``` field in saved hdf5 files they are actually all 0 and float 32. Also, ```['spectra']['axis']``` are all float32 instead of int.  So, probably fake_spectra does not print these information properly.  I am going to check the fake_spectra.

**Comment by sbird** [comment]
Strange we never noticed that before! Definitely a bug, either in saving the hdf5 file or in randspectra.

**Comment by qezlou** [comment]
I am so sorry, my bad! When I was running the parallel code, I have forgotten to update cofm and axis. I am going to run the vw_spectra on non-parallel runs on your snapshots to see  if it's working well.

**Comment by sbird** [comment]
Ok! That's fine, glad you found it.

**Pull request merged**
